server: port=8080

spring:
  application:
    name: ASM_keycloak
  datasource:
    url: jdbc:postgresql://localhost:6543/custom-provider
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/viettien

idp:
  url: http://localhost:9090/
  client-id: springboot-app
  client-secret: KxTxeDCdTkBEe5hINro8AE5WgI5DFfE0